name: Spring Boot CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build and Test
        run: ./mvnw clean verify

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-application
          path: target/*.jar

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=sakthirangasamy
            -Dsonar.projectKey=sakthirangasamy_GithubAction-CI-CD-Setup-ECS

      - name: OWASP Dependency-Check
        run: |
          ./mvnw dependency-check:check

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report